language: node_js
node_js:
- '0.8'
- '0.10'
script: ./run_tests.sh
notifications:
  email: false
  irc:
  - irc.freenode.org#statsd
deploy:
  provider: npm
  email: d@unwiredcouch.com
  api_key:
    secure: IE9nz50eZsRL1Dbcxj2eY0apO1Io2swGF3ezZCzny20WgqQXiiVs24rHUi1GywDELGDc7+Vp0zJfmXigE+zTMvx0N3fTASiuDzd3C7fULa4JUSH2DoHNOXx7WSkr4EmujDsB7y1mEBDHOdBlLWBRApExt67TlYzvZiT8/Sffq3k=
  on:
    tags: true
    repo: etsy/statsd
